### ISSUE TITLE
Roadmap: Major-0 (Core)

### ISSUE THREAD

**Issue by KarasuTatehi** [RWPT/markov#1]
Markovコア機能の実装

## 変更点

- [ ] 追加: プレイヤーデータ
  - [ ] プレイヤータグ（Discordのユーザー名とポーカーチェイスのプレイヤー名の紐付け）
  - [ ] 戦績・統計
- [ ] 追加: 部屋管理
  - [ ] 部屋情報（上限、初期チップ、ストラクチャー、ターン制限時間、部屋番号など）
  - [ ] ウェイティングリスト（予約状況、出欠確認）
  - [ ] トランザクション（着順の提出・確定）
